spring:
  profiles:
    group:
      dev: common, dev
      prod: common, prod

---
spring:
  config:
    activate:
      on-profile: "common"
  application:
    name: demo
  sql:
    init:
      platform: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/kfriday?serverTimezone=Asia/Seoul
    username: root
    password: Password1!
    driver-class-name: com.mysql.cj.jdbc.Driver


spring.sql.init.platform: mysql
server:
  port: 9000
  error:
    include-message: always
    include-binding-errors: always

---
spring:
  config:
    activate:
      on-profile: "prod"
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true

---
spring:
  config:
    activate:
      on-profile: "dev"
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
